spring:
  banner:
    location: banner.txt
  profiles:
    active: ${ACTIVE_PROFILE}
  security:
    oauth2:
      client:
        registration:
          github:
            scope: read:email # only public
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
  jpa:
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    show-sql: false
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: non_empty
    serialization:
      fail-on-empty-beans: false
---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3308/sudodev?useSSL=false
    username: developer
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
logging:
  level:
#    ROOT: trace
---

spring:
  profiles: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USER}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
