spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sudocodedb?useSSL=false
    username: sudocode_admin # ${SPRING_DATASOURCE_USER}
    password: password # ${SPRING_DATASOURCE_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          github:
            scope: read:email # only public
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    show-sql: false
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: non_empty
    serialization:
      fail-on-empty-beans: false

---

spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:3308/sudocode_test?useSSL=false
    username: admin
    password: password

