app:
  title: @project.name@
  version: @project.version@
  JDK: @java.version@

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            scope: read:email # only public
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
  jpa:
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    show-sql: false
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: non_empty
    serialization:
      indent-output: true
      fail-on-empty-beans: false
    deserialization:
      accept-single-value-as-array: true
  profiles:
    active: ${ACTIVE_PROFILE}

management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include:
          - health
          - info
server:
  port: ${PORT}
---

spring:
  profiles: dev
  datasource:
    url: ${SPRING_DB_URL} #jdbc:mysql://localhost:3308/sudodev?useSSL=false
    username: ${SPRING_DB_USER} #developer
    password: ${SPRING_DB_PASS} #password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
logging:
  level:
    org.sudocode.api: debug
    org.springframework.web: trace
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
#server:
#  error:
#    whitelabel:
#      enabled: false
#    path: '/error'
management.endpoints:
  web:
    exposure:
      include: '*'
---

spring:
  profiles: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test