version: '3'

services:

  mysql-test:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sudocode_test
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
    - "3308:3306"